src/queries/index.js

- [] I have made corresponding changes to the documentation

create addMood query and update user queries

---

package.json
public/index.html
src/components/Logo.js
src/components/MoodPreview.js
src/components/NavBuffet.js
src/containers/App/App.js
src/containers/Dashboard/Dashboard.js
src/containers/EntryForm/EntryForm.js
yarn.lock

Entry form built and basic components in place

---

public/index.html
public/main.js
public/manifest.json
public/mm-service-worker.js
src/index.js
src/utils/serviceWorker.js

Service workers

---

src/components/FormViews.js
src/components/Login.js
src/components/Logout.js
src/containers/EntryForm/EntryForm.js
src/containers/Settings/Settings.js
src/containers/Welcome/Welcome.js

- [x ] New feature (non-breaking change which adds functionality)
- [ x] Complete, but not tested (may need new tests)
- [x ] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ x] My code has been reviewed by at least one peer

Adding styles for formviews, welcome, and settings

---

src/components/FormViews.js
src/components/MoodDisplay.js
src/components/MoodPreview.js
src/components/WeekDisplay.js
src/containers/Moods/Moods.js
src/containers/SingleDay/SingleDay.js
src/containers/SingleDay/index.js
src/utils/convertDay.js
src/utils/weekOfMoods.js

Add weekday display, single day view rendering mood display, week display showing mood previews from the past week

Week preview display added

---

src/utils/convertTemp.js

removes an unused function from utils

remove convertTemp function

---

package.json
src/index.js
src/utils/config.js
yarn.lock

Installed Google Analytics and added tracking for pageviews

Add Analytics for Staging & Production

---

src/containers/App/App.js

changed routes to private routes

---

src/components/MoodPreview.js
src/containers/Dashboard/Dashboard.js

Preview text now truncated to one line with ellipsis if necessary. Navbar no longer cuts off dashboard mood cards.
Fixes #32 

Preview text truncated & dashboard styling tweaks

---

package.json
src/__tests__/Activities.test.js
src/__tests__/Activity.test.js
src/__tests__/FormActivityJournal.test.js
src/__tests__/FormAnxietySleep.test.js
src/__tests__/__snapshots__/FormAnxietySleep.test.js.snap

Fixes issues with ant design compatibility by adding a special script to the test script, did FormAnxietySleep tests but ant design slider is super harder to mock
- [ x] New feature (non-breaking change which adds functionality)
- [x ] Complete, tested, ready to review and merge
It's a test.
- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] My changes generate no new warnings
- [x ] I have added tests that prove my fix is effective or that my feature works
- [x ] New and existing unit tests pass locally with my changes
- [x ] There are no merge conflicts

Fix issues with ant design compatibility and add FormAnxietySleep tests

---

public/index.html
src/components/MoodDisplay.js
src/hooks/useCurrentWeather.js

Fixes issue where there was a brief momentary flash of text showing no moods for day on the initial render of the `MoodDisplay` component.

fix flash of text on the single day mood view

---

package.json
src/components/GAListener.js
src/containers/App/App.js
src/index.js
yarn.lock

fix page tracking/history issue.

fix page tracking/history issue

---

src/containers/Dashboard/icons/TasksIcon.js
src/utils/config.js

Navbar icons

---

public/index.html
src/components/MobileNavBar.js
src/components/MoodCard.js
src/components/MoodDisplay.js

style mood cards and fixed navbar

---

src/components/Login.js
src/components/MobileNavBar.js
src/components/MoodCard.js
src/components/MoodDisplay.js
src/containers/App/App.js
src/containers/Welcome/Welcome.js

Fixed too-small card layout in mood card, cleaned up styling in mood display, fixed issue with routing where mood wasn't always highlighted when active, added styles and layout to welcome page. Welcome page image still needs to be added.
Fixes #57 

Styling fixes & welcome page layout

---

README.md
src/__tests__/__snapshots__/MoodCard.test.js.snap
src/components/MoodDisplay.js

Reimports styles that were removed in a previous commit that caused the build to fail.  Also updates the readme with a couple of badges.

fix failed build from removing necessary import

---

src/containers/Settings/Settings.js

Change the default background color of the switch component on the settings tab.

change settings switch bg color

---

src/components/MoodCard.js
src/components/WeekDisplay.js
src/containers/Moods/Moods.js

Updated mood card & dashboard styling, fixed padding issues

---

src/components/Auth/SignIn.js
src/components/Auth/SignUp.js
src/components/Auth/auth.styles.js
src/components/Auth/axiosAuth/axios.js

- Adds a spinner loading indicator in the buttons in the `Signup` and `Signin` components
- Adds an error alert banner whenever backend returns an error on signin and signup
- adjusted some styles including the `.or` separator styling
Fixes #70 

basic error handling on signin and signup errors

---

package.json
src/components/Auth/SignIn.js
src/components/Auth/axiosAuth/axios.js
src/containers/Settings/Logout.js
src/containers/Welcome/Welcome.js
src/index.js
src/utils/dataStore.js
yarn.lock

Added function that gets token from URL query string. 
- Tested manually

Added function that gets token from URL query string. 

---

src/utils/dataStore.js

remove console logs and unused import

---

src/components/DailyTask/TaskComplete.js

fix issue with height on task complete page on mobile

---

src/components/DailyTask/TaskComplete.js
src/containers/Dashboard/Dashboard.js

Fix issue where height of Task Complete page wasn't 100% height.  Changed `.dashboard-main` from `min-height: 100%` to `height: 100%`
Fixes #85 

actually fix the height issue on task complete

---

src/components/FormViews/Activities.js

add dots to activities

---

src/utils/dataStore.js

fix the check for the token expiration date in initAuth function in dataStore

fix token bug in initAuth

---

src/components/Auth/axiosAuth/axios.js

Adds more descriptive error messages
Fixes #70 

updates to auth error handling

---

README.md

updatin the readme like a bawse

---

src/components/DailyTask/Task.js
src/components/DailyTask/TaskWheel.js
src/components/DailyTask/tasks.js

Add writing prompts and picture prompts to the the tasks.

add task prompts and picture prompt

---

src/components/DailyTask/Task.js
src/components/DailyTask/TaskWheel.js
src/components/DailyTask/tasks.js

updated styles on task section

---

src/components/ExportPdf/AllMoodsPdf.js
src/components/ExportPdf/MonthPdf.js
src/components/ExportPdf/WeekPdf.js

Updating PDF Export displayed name for users

---

src/components/FormViews/Activities.js
src/components/FormViews/ActivityTag.js

change padding, margin and justify-content of activity tags

---

src/components/DayDisplay.js

fixed deleteTask function name

---

public/index.html
src/index.js

Adding custom service back in
